### ISSUE TITLE
Need to protect jobs from respawning

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-management#6]

**Comment by makentenza** [comment]
@etsauer have you seen this behaviour somewhere apart from `cronjob-ldap-group-sync.yml`?

**Comment by makentenza** [comment]
Solved this on #24. Will update that PR in case we have more examples of this happening. So far this is the only Job I have seen with this behaviour.

**Comment by oybed** [comment]
Fixed with #24 - closing
